{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "from tkinter import *\n",
    "import matplotlib\n",
    "matplotlib.use('TkAgg')\n",
    "import seaborn as sns\n",
    "from matplotlib.figure import Figure\n",
    "from matplotlib.backends.backend_tkagg import (FigureCanvasTkAgg, NavigationToolbar2Tk)\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import datetime\n",
    "from textwrap import wrap\n",
    "\n",
    "\n",
    "# read files\n",
    "track_length_combined = pd.read_csv('https://jroefive.github.io/track_length_combined')\n",
    "set_placement = pd.read_csv('https://jroefive.github.io/set_placement_plot')\n",
    "\n",
    "# Combine inputs into a datetime variable and retrieve the ID number for that show\n",
    "def get_show_date(year,month,day):\n",
    "    show_date = datetime.date(year, month, day)\n",
    "    sd = str(show_date)\n",
    "    show_played = True\n",
    "    # Make sure the date input is in the database\n",
    "    if sd in track_length_combined['date'].values:\n",
    "        show_date_id = track_length_combined[track_length_combined['date']==sd]['order_id'].values\n",
    "        # Previous line creates a series of the same ID values, so need to reset to equal just the first value.\n",
    "        show_date_id = show_date_id[0]\n",
    "    # If the show doesn't exist, set show_played to false so other functions won't run\n",
    "    else:\n",
    "        show_played = False\n",
    "        show_date_id = 1\n",
    "    return show_date, show_date_id, show_played\n",
    "\n",
    "# Pull a list of all songs in each set of show\n",
    "def get_setlist(show_date_id):\n",
    "    show_only = track_length_combined[(track_length_combined['order_id']==show_date_id)]\n",
    "    show_only = show_only.sort_values(by='position')\n",
    "    show_songs_s1 = show_only[show_only['set']=='1']['title'].values\n",
    "    show_songs_s2 = show_only[show_only['set']=='2']['title'].values\n",
    "    show_songs_s3 = show_only[show_only['set']=='3']['title'].values\n",
    "    show_songs_e = show_only[(show_only['set']=='E') | (show_only['set']=='E2')]['title'].values\n",
    "    return show_songs_s1, show_songs_s2, show_songs_s3, show_songs_e\n",
    "\n",
    "# Create Graphs\n",
    "def get_graph(set_songs, show_date, show_date_id, hue_choice, graph_type):\n",
    "    \n",
    "    # Update hue list and order and make sure to include selected show\n",
    "    hue_list = ('Before', 'Previous 50 Shows', show_date, 'Next 50 Shows', 'After')\n",
    "    hue_choice.append(show_date)\n",
    "    hue_order = []\n",
    "    for hue in hue_list:\n",
    "        if hue in hue_choice:\n",
    "            hue_order.append(hue)\n",
    "    \n",
    "    # Select the correct data dependent on graph type\n",
    "    if graph_type == 'dur':\n",
    "        tracks_from_set = track_length_combined[track_length_combined['title'].isin(set_songs)].copy()\n",
    "    elif graph_type == 'place':\n",
    "        tracks_from_set = set_placement[set_placement['title'].isin(set_songs)].copy()\n",
    "    \n",
    "    # Create timing column to color code graph by recent shows\n",
    "    tracks_from_set.loc[tracks_from_set['order_id'] < show_date_id, 'timing'] = 'Before'\n",
    "    tracks_from_set.loc[tracks_from_set['order_id'] > show_date_id, 'timing'] = 'After'\n",
    "    tracks_from_set.loc[(tracks_from_set['order_id'] > show_date_id) & (tracks_from_set['order_id'] - (show_date_id + 50) <= 0), 'timing'] = 'Next 50 Shows'\n",
    "    tracks_from_set.loc[(tracks_from_set['order_id'] < show_date_id) & (tracks_from_set['order_id'] - (show_date_id - 50) >= 0), 'timing'] = 'Previous 50 Shows'\n",
    "    tracks_from_set.loc[tracks_from_set['order_id'] == show_date_id, 'timing'] = show_date\n",
    "    \n",
    "    # Drop all timing values that weren't selected\n",
    "    tracks_from_set = tracks_from_set[tracks_from_set['timing'].isin(hue_choice)]\n",
    "    \n",
    "    # Color palette so the colors stay consistent for all timing choices\n",
    "    palette = {\"Before\":\"#E8E0DE\", \"Previous 50 Shows\":\"#2C6E91\", show_date:\"#000000\", \"Next 50 Shows\":\"#F15A50\", \"After\":\"#DEE8E4\"}\n",
    "    \n",
    "    # Create figure, add subplot and set x values since both graphs have same x value\n",
    "    graph = Figure(figsize = (12.5,5))\n",
    "    graph.patch.set_facecolor('#2C6E91')\n",
    "    ax = graph.add_subplot(111)\n",
    "    \n",
    "    \n",
    "    # Plot duration graph and set y axis label to be duration\n",
    "    if graph_type == 'dur':\n",
    "        sns.swarmplot(x=\"title\", y=\"duration\", hue = 'timing', hue_order = hue_order, order = set_songs, data=tracks_from_set, \n",
    "            palette=palette, ax=ax)\n",
    "        ax.set_ylabel('Song Duration in Minutes', fontname=\"Arial\", fontsize=18)\n",
    "        \n",
    "    # Plot set placement graph, set y axis label to be set placement, and rename yticklabels to make it clearer what set placement mean\n",
    "    elif graph_type == 'place':\n",
    "        sns.swarmplot(x=\"title\", y=\"percentintoset\", hue = 'timing', hue_order = hue_order, order = set_songs, data=tracks_from_set, \n",
    "            palette=palette, ax=ax)\n",
    "        ax.set_ylabel('Set Placement', fontname=\"Arial\", fontsize=18)\n",
    "        ytick_list = ax.get_yticks().tolist()\n",
    "        for n,i in enumerate(ytick_list):\n",
    "            if i == 1:\n",
    "                ytick_list[n] = 'Start Set 1'\n",
    "            elif i == 1.5:\n",
    "                ytick_list[n] = 'Middle Set 1'\n",
    "            elif i == 2:\n",
    "                ytick_list[n] = 'Start Set 2'\n",
    "            elif i == 2.5:\n",
    "                ytick_list[n] = 'Middle Set 2'\n",
    "            elif i == 3:\n",
    "                ytick_list[n] = 'Start Set 3'\n",
    "            elif i == 3.5:\n",
    "                ytick_list[n] = 'Middle Set 3'\n",
    "            elif i == 4:\n",
    "                ytick_list[n] = 'Start Encore'\n",
    "            elif i == 4.5:\n",
    "                ytick_list[n] = 'Middle Encore'\n",
    "            elif i == 5:\n",
    "                ytick_list[n] = 'End of Show'\n",
    "        ax.set_yticklabels(ytick_list, fontname=\"Arial\", fontsize=12)\n",
    "    \n",
    "    # Rotate and wrap song title labels\n",
    "    ax.set_xlabel('Song Title', fontname=\"Arial\", fontsize=18)\n",
    "    labels = set_songs\n",
    "    labels = [ '\\n'.join(wrap(l, 10)) for l in labels ]\n",
    "    ax.set_xticklabels(labels,rotation=45, fontname=\"Arial\", fontsize=12)\n",
    "    \n",
    "    # Placement of legend and create enough space at bottom for song titles.\n",
    "    ax.legend(loc='upper center', bbox_to_anchor=(0.5, 1.05), ncol=5, fancybox=True, shadow=True)\n",
    "    graph.subplots_adjust(bottom=0.3)\n",
    "    ax.spines['bottom'].set_color('#F15A50')\n",
    "    ax.spines['top'].set_color('#F15A50')\n",
    "    ax.xaxis.label.set_color('#F15A50')\n",
    "    ax.tick_params(axis='x', colors='#F15A50')\n",
    "    ax.spines['left'].set_color('#F15A50')\n",
    "    ax.spines['right'].set_color('#F15A50')\n",
    "    ax.yaxis.label.set_color('#F15A50')\n",
    "    ax.tick_params(axis='y', colors='#F15A50')\n",
    "    \n",
    "    return graph\n",
    "\n",
    "# Template for TK pages\n",
    "class Template(Tk):\n",
    "    def __init__(self, *args, **kwargs):\n",
    "        Tk.__init__(self, *args, **kwargs)\n",
    "        container = Frame(self)\n",
    "        container.pack(side=\"top\", fill=\"both\", expand = True)\n",
    "        \n",
    "        self.frames = {}\n",
    "\n",
    "\n",
    "        for F in (InputPage, SetlistPage):\n",
    "            frame=F(container, self)\n",
    "            self.frames[F]=frame\n",
    "            frame.grid(row=0, column=0, sticky=\"nsew\")\n",
    "\n",
    "            self.show_frame(InputPage)\n",
    "    \n",
    "    def show_frame(self, page):\n",
    "        frame = self.frames[page]\n",
    "        frame.tkraise()\n",
    "\n",
    "    def get_page(self, page_class):\n",
    "        return self.frames[page_class]\n",
    "\n",
    "# Main page of app\n",
    "class InputPage(Frame):\n",
    "    def __init__(self, parent, controller):\n",
    "        Frame.__init__(self, parent)\n",
    "        self.controller=controller\n",
    "        # Set some global variables\n",
    "        self.month = ''\n",
    "        self.day = ''\n",
    "        self.year = ''\n",
    "        self.show_date = ''\n",
    "        self.show_date_id = 0\n",
    "        global set_for_graph\n",
    "        self.set_for_graph = IntVar()\n",
    "        self.set_for_graph.set(1)\n",
    "        self.hues = ('Before', 'Previous 50 Shows', 'Next 50 Shows', 'After')\n",
    "        self.hue_choice = []\n",
    "        self.config(bg=\"#2C6E91\")\n",
    "        # Reset the date, chosen set, and timing choices every time a graph or setlist is requested\n",
    "        \n",
    "        def reset_date():\n",
    "            self.graph_frame.destroy()  \n",
    "            self.pane6.destroy()\n",
    "            self.pane7.destroy()\n",
    "            self.pane8.destroy()\n",
    "            self.pane9.destroy()\n",
    "            self.pane_error.destroy()\n",
    "            self.month = int(month.get())\n",
    "            self.day = int(day.get())\n",
    "            self.year = int(year.get())\n",
    "            self.set_for_graph_int = self.set_for_graph.get()\n",
    "            self.show_date, self.show_date_id, self.show_played = get_show_date(self.year,self.month,self.day)\n",
    "            if not self.show_played:\n",
    "                self.pane_error = Frame(self, bg=\"#2C6E91\")\n",
    "                self.pane_error.pack(side = TOP, fill = BOTH, expand = True, padx = 10, pady = 10)\n",
    "                Label(self.pane_error, text=\"Phish did not play a show on \" + str(self.show_date) + '. Or that show is not available in this database.', bg=\"#2C6E91\", fg = '#F15A50', font = ('ARial 18 bold')).pack( side = LEFT, fill = BOTH, expand = 1)\n",
    "            self.hue_choice = []\n",
    "            for ix, hue in enumerate(self.hues):\n",
    "                if hue_vars[ix].get():\n",
    "                    self.hue_choice.append(hue)\n",
    "        \n",
    "        # Update setlist panes when setlist is requested\n",
    "        def print_setlist(): \n",
    "            if self.show_played:\n",
    "                self.pane6 = Frame(self, bg=\"#2C6E91\") \n",
    "                self.pane6.pack(fill = BOTH, expand = True)\n",
    "                self.pane7 = Frame(self, bg=\"#2C6E91\") \n",
    "                self.pane7.pack(fill = BOTH, expand = True)\n",
    "                self.pane8 = Frame(self, bg=\"#2C6E91\") \n",
    "                self.pane8.pack(fill = BOTH, expand = True)\n",
    "                self.pane9 = Frame(self, bg=\"#2C6E91\") \n",
    "                self.pane9.pack(fill = BOTH, expand = True)\n",
    "            \n",
    "                Label(self.pane6, text='Set 1:', bg=\"#2C6E91\", fg = '#F15A50', font = ('Arial', 18)).pack( side = LEFT, padx = 5, pady = 5)\n",
    "                self.set1 = Label(self.pane6, text='', bg=\"#2C6E91\", fg = '#F15A50', font = ('ARial 18 bold'))\n",
    "                self.set1.pack( side = LEFT, expand = True)\n",
    "        \n",
    "                Label(self.pane7, text='Set 2:', bg=\"#2C6E91\", fg = '#F15A50', font = ('Arial', 18)).pack( side = LEFT, padx = 5, pady = 5)\n",
    "                self.set2 = Label(self.pane7, text='', bg=\"#2C6E91\", fg = '#F15A50', font = ('ARial 18 bold'))\n",
    "                self.set2.pack( side = LEFT, expand = True)\n",
    "        \n",
    "                Label(self.pane8, text='Set 3:', bg=\"#2C6E91\", fg = '#F15A50', font = ('Arial', 18)).pack( side = LEFT, padx = 5, pady = 5)\n",
    "                self.set3 = Label(self.pane8, text='', bg=\"#2C6E91\", fg = '#F15A50', font = ('ARial 18 bold'))\n",
    "                self.set3.pack( side = LEFT, expand = True)\n",
    "        \n",
    "                Label(self.pane9, text='Encore:', bg=\"#2C6E91\", fg = '#F15A50', font = ('Arial', 18)).pack( side = LEFT, padx = 5, pady = 5)\n",
    "                self.enc = Label(self.pane9, text='', bg=\"#2C6E91\", fg = '#F15A50', font = ('ARial 18 bold'))\n",
    "                self.enc.pack( side = LEFT, expand = True)\n",
    "            \n",
    "                self.s1, self.s2, self.s3, self.e = get_setlist(self.show_date_id)\n",
    "                self.set1.config(text=self.s1)\n",
    "                self.graph_frame.destroy()      \n",
    "                self.graph_frame = Frame(self)\n",
    "                self.graph_frame.pack(fill = BOTH, expand = True)\n",
    "                if len(self.s2) > 0:\n",
    "                    self.set2.config(text=self.s2)\n",
    "                if len(self.s3) > 0:\n",
    "                    self.set3.config(text=self.s3)\n",
    "                if len(self.e) > 0:\n",
    "                    self.enc.config(text=self.e)\n",
    "        \n",
    "        # Show graph command on button push\n",
    "        def show_graph(graph_type):\n",
    "            if self.show_played:\n",
    "                # Get setlist\n",
    "                self.s1, self.s2, self.s3, self.e = get_setlist(self.show_date_id)\n",
    "                # Destory any previous graphs before graphing again    \n",
    "                self.graph_frame = Frame(self)\n",
    "                self.graph_frame.pack(fill = BOTH, expand = True)\n",
    "                # If statement to input correct set, call get_graph, then draw graph\n",
    "                if self.set_for_graph_int == 1 and len(self.s1)>0:\n",
    "                    self.g1 = get_graph(self.s1, self.show_date, self.show_date_id, self.hue_choice, graph_type)\n",
    "                    canvas = FigureCanvasTkAgg(self.g1, self.graph_frame)\n",
    "                    canvas.draw()\n",
    "                    set1plot = canvas.get_tk_widget()\n",
    "                    set1plot.pack(side = LEFT)\n",
    "                if self.set_for_graph_int == 2 and len(self.s2)>0:\n",
    "                    self.g2 = get_graph(self.s2, self.show_date, self.show_date_id, self.hue_choice, graph_type)\n",
    "                    canvas = FigureCanvasTkAgg(self.g2, master = self.graph_frame)\n",
    "                    canvas.draw()\n",
    "                    canvas.get_tk_widget().pack(side = LEFT)\n",
    "                if self.set_for_graph_int == 3 and len(self.s3)>0:\n",
    "                    self.g3 = get_graph(self.s3, self.show_date, self.show_date_id, self.hue_choice, graph_type)\n",
    "                    canvas = FigureCanvasTkAgg(self.g3, master = self.graph_frame)\n",
    "                    canvas.draw()\n",
    "                    canvas.get_tk_widget().pack()\n",
    "                if self.set_for_graph_int == 4 and len(self.e)>0:\n",
    "                    self.ge = get_graph(self.e, self.show_date, self.show_date_id, self.hue_choice, graph_type)\n",
    "                    canvas = FigureCanvasTkAgg(self.ge, master = self.graph_frame)\n",
    "                    canvas.draw()\n",
    "                    canvas.get_tk_widget().pack()\n",
    "                else:\n",
    "                    self.pane_error = Frame(self, bg=\"#2C6E91\")\n",
    "                    self.pane_error.pack(side = TOP, fill = BOTH, expand = True, padx = 10, pady = 10)\n",
    "                    Label(self.pane_error, text=\"Phish didn't play a Set \" + str(self.set_for_graph_int) + \" on \" + str(self.show_date) + '.', bg=\"#2C6E91\", fg = '#F15A50', font = ('ARial 18 bold')).pack( side = LEFT, fill = BOTH, expand = 1)\n",
    "        \n",
    "        # Labels and inputs for show date\n",
    "        pane1 = Frame(self) \n",
    "        pane1.pack(side = TOP, fill = BOTH, expand = True, padx = 10, pady = 10)\n",
    "        pane1.config(bg=\"#2C6E91\")\n",
    "        Label(pane1, text=\"Input Show Date:\", bg=\"#2C6E91\", fg = '#F15A50', font = ('ARial 18 bold')).pack( side = LEFT, expand = True, fill = BOTH)\n",
    "        Label(pane1, text=\"Month\", bg=\"#2C6E91\", fg = '#F15A50', font = ('ARial 18 bold')).pack( side = LEFT, expand = True, fill = BOTH, padx = 5, pady = 5)\n",
    "        month = Entry(pane1, bg=\"#2C6E91\", fg = '#F15A50', font = ('ARial 18 bold'), justify ='center')\n",
    "        month.insert(0,'12')\n",
    "        month.pack( side = LEFT, fill = BOTH)\n",
    "        Label(pane1, text=\"Day\", bg=\"#2C6E91\", fg = '#F15A50', font = ('ARial 18 bold')).pack( side = LEFT, expand = True, fill = BOTH, padx = 5, pady = 5)\n",
    "        day = Entry(pane1, bg=\"#2C6E91\", fg = '#F15A50', font = ('ARial 18 bold'), justify ='center')\n",
    "        day.insert(0,'31')\n",
    "        day.pack( side = LEFT, fill = BOTH)\n",
    "        Label(pane1, text=\"Year\", bg=\"#2C6E91\", fg = '#F15A50', font = ('ARial 18 bold')).pack( side = LEFT, expand = True, fill = BOTH, padx = 5, pady = 5)\n",
    "        year = Entry(pane1, bg=\"#2C6E91\", fg = '#F15A50', font = ('ARial 18 bold'), justify ='center')\n",
    "        year.insert(0,'1999')\n",
    "        year.pack( side = LEFT, fill = BOTH)\n",
    "        \n",
    "        \n",
    "        # Labels and inputs for which set to graph\n",
    "        pane2 = Frame(self, bg=\"#2C6E91\") \n",
    "        pane2.pack(side = TOP, fill = BOTH, expand = True, padx = 10, pady = 10)\n",
    "        Label(pane2, text=\"Choose a Set for Graph:\", bg=\"#2C6E91\", fg = '#F15A50', font = ('ARial 18 bold')).pack( side = LEFT, fill = BOTH)\n",
    "        Radiobutton(pane2, text='Set 1', variable=self.set_for_graph, value=1, bg=\"#2C6E91\", fg = '#F15A50', font = ('ARial 18 bold')).pack( side = LEFT, fill = BOTH, expand = 1)\n",
    "        Radiobutton(pane2, text='Set 2', variable=self.set_for_graph, value=2, bg=\"#2C6E91\", fg = '#F15A50', font = ('ARial 18 bold')).pack( side = LEFT, fill = BOTH, expand = 1)\n",
    "        Radiobutton(pane2, text='Set 3', variable=self.set_for_graph, value=3, bg=\"#2C6E91\", fg = '#F15A50', font = ('ARial 18 bold')).pack( side = LEFT, fill = BOTH, expand = 1)\n",
    "        Radiobutton(pane2, text='Encore', variable=self.set_for_graph, value=4, bg=\"#2C6E91\", fg = '#F15A50', font = ('ARial 18 bold')).pack( side = LEFT, fill = BOTH, expand = 1)\n",
    "\n",
    "\n",
    "        # Checkbuttons for which shows to include\n",
    "        pane3 = Frame(self, bg=\"#2C6E91\") \n",
    "        pane3.pack(side = TOP, fill = BOTH, expand = True, padx = 10, pady = 10)\n",
    "        Label(pane3, text=\"Filter Shows For Graph:\", bg=\"#2C6E91\", fg = '#F15A50', font = ('ARial 18 bold')).pack(side = LEFT)\n",
    "        hue_buttons = list(range(len(self.hues)))\n",
    "        hue_vars = list(range(len(self.hues)))\n",
    "        for ix, text in enumerate(self.hues):\n",
    "            hue_vars[ix] = IntVar()\n",
    "            hue_vars[ix].set(1)\n",
    "            hue_buttons[ix] = Checkbutton(pane3, text=text, variable = hue_vars[ix],bg=\"#2C6E91\", fg = '#F15A50', font = ('ARial 18 bold'))\n",
    "            hue_buttons[ix].pack(side = LEFT, expand = 1)\n",
    "        \n",
    "        pane5 = Frame(self, bg=\"#2C6E91\") \n",
    "        pane5.pack(side = TOP, fill = BOTH, expand = True, padx = 10, pady = 10) \n",
    "        \n",
    "        # Buttons to generate graphs\n",
    "        Button(pane5, text=\"Check Setlist\", command=lambda:[reset_date(),print_setlist()], bg=\"#2C6E91\", fg = '#F15A50', font = ('ARial 18 bold')).pack( side = LEFT, fill = BOTH, expand = 1)\n",
    "        Button(pane5, text=\"Show Song Duration Graph\", command=lambda:[reset_date(),show_graph('dur')], bg=\"#2C6E91\", fg = '#F15A50', font = ('ARial 18 bold')).pack( side = LEFT, fill = BOTH, expand = 1)\n",
    "        Button(pane5, text=\"Show Set Placement Graph\", command=lambda:[reset_date(),show_graph('place')], bg=\"#2C6E91\", fg = '#F15A50', font = ('ARial 18 bold')).pack( side = LEFT, fill = BOTH, expand = 1)\n",
    "        \n",
    "        # Frames for setlist display\n",
    "        self.pane6 = Frame(self, bg=\"#2C6E91\") \n",
    "        self.pane6.pack(fill = BOTH, expand = True)\n",
    "        self.pane7 = Frame(self, bg=\"#2C6E91\") \n",
    "        self.pane7.pack(fill = BOTH, expand = True)\n",
    "        self.pane8 = Frame(self, bg=\"#2C6E91\") \n",
    "        self.pane8.pack(fill = BOTH, expand = True)\n",
    "        self.pane9 = Frame(self, bg=\"#2C6E91\") \n",
    "        self.pane9.pack(fill = BOTH, expand = True)\n",
    "        self.graph_frame = Frame(self,bg = \"#2C6E91\")\n",
    "        self.graph_frame.pack(fill = BOTH, expand = True)\n",
    "        self.pane_error = Frame(self,bg = \"#2C6E91\")\n",
    "        self.pane_error.pack(fill = BOTH, expand = True)\n",
    "        \n",
    "class SetlistPage(Frame):\n",
    "    def __init__(self, parent, controller):\n",
    "        Frame.__init__(self, parent)\n",
    "        self.controller=controller\n",
    "\n",
    "\n",
    "master = Template()\n",
    "master.title(\"Phish Show Digest App\")\n",
    "\n",
    "\n",
    "master.mainloop()\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
